-- Enable RLS (if not already)
alter table reviews enable row level security;
alter table sentiment_analysis enable row level security;

-- Create alerts table
create table if not exists alerts (
  id bigint generated by default as identity primary key,
  type text not null,
  severity text not null, -- 'critical', 'high', 'medium', 'low'
  title text not null,
  message text not null,
  platform text,
  is_read boolean default false,
  is_resolved boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  details jsonb
);

-- Create user_settings table
create table if not exists user_settings (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Links to auth.users or just a string ID
  key text not null,
  value text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, key)
);

-- Create integrations table
create table if not exists integrations (
  id bigint generated by default as identity primary key,
  platform text not null unique, -- 'twitter', 'reddit', 'youtube', 'huggingface'
  status text default 'inactive', -- 'active', 'inactive', 'error'
  last_sync timestamp with time zone,
  api_key text, -- Encrypted in real app, plain for demo
  is_enabled boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create topic_analysis table
create table if not exists topic_analysis (
  id bigint generated by default as identity primary key,
  topic_name text not null,
  sentiment numeric,
  size integer,
  keywords text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on new tables
alter table alerts enable row level security;
alter table user_settings enable row level security;
alter table integrations enable row level security;
alter table topic_analysis enable row level security;

-- Create Open Access Policies (For Demo/Dev Environment - simplistic)
create policy "Enable all access for alerts" on alerts for all using (true) with check (true);
create policy "Enable all access for user_settings" on user_settings for all using (true) with check (true);
create policy "Enable all access for integrations" on integrations for all using (true) with check (true);
create policy "Enable all access for topic_analysis" on topic_analysis for all using (true) with check (true);

-- Create a function to calculate dashboard stats efficiently in DB
create or replace function get_dashboard_stats()
returns json
language plpgsql
as $$
declare
  total_count integer;
  avg_sentiment numeric;
  avg_credibility numeric;
  platform_counts json;
begin
  -- Get total reviews
  select count(*) into total_count from reviews;

  -- Get Average Sentiment (Mapped: POSITIVE=1, NEUTRAL=0.5, NEGATIVE=0)
  -- and Average Credibility
  select 
    coalesce(avg(
      case 
        when label = 'POSITIVE' then 100 
        when label = 'NEUTRAL' then 50 
        else 0 
      end
    ), 0),
    coalesce(avg(credibility), 0)
  into avg_sentiment, avg_credibility
  from sentiment_analysis;

  -- Get Platform Breakdown
  select json_object_agg(platform, count)
  into platform_counts
  from (
    select platform, count(*) as count
    from reviews
    group by platform
  ) p;

  return json_build_object(
    'totalReviews', total_count,
    'sentimentScore', avg_sentiment,
    'averageCredibility', avg_credibility,
    'platformBreakdown', platform_counts
  );
end;
$$;
